# Theme Settings
remote_theme: "mmistakes/minimal-mistakes@4.27.1"
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale: "en-US"
title: "Your Site Title"
title_separator: "-"
subtitle: "Your Subtitle"
name: "Your Name"
description: "Your personal website description"
url: "https://nazmicancalik.github.io"
baseurl: ""
repository: "nazmicancalik/nazmicancalik.github.io"

# Site Author
author:
  name: "Your Name"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "Your bio goes here"
  location: "Your Location"
  email: "your.email@example.com"
  links:
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin-square"
      url: "https://linkedin.com/in/nazmicancalik"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/nazmicancalik"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true